export const Allprojects = [
  {
    title: "Android App",
    projects: [
      {
        name: "Xenea wallet",
        funding: "NOA",
        backers: "Xenea",
        expectedTGE: "Q1 2025",
        joinLink: "https://xenea.app/register/15NbfWpl2G",
        refCode: "15NbfWpl2G",
        logo: "projectLogo/xenea-logo.png",
      },
      {
        name: "Chirp",
        funding: "TBA",
        backers: "Sui Foundation",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://chirp.app/referral-code=vinith103",
        refCode: "vinith103",
        logo: "projectLogo/chirp-logo.png",
      },
    ],
  },
  {
    title: "Telegram bots",
    projects: [
      {
        name: "Sigma",
        funding: "$4.2M",
        backers: "Not officially mentioned",
        expectedTGE: "Q2",
        joinLink: "https://t.me/sigmatonbot/app?startapp=ref_2d9x5de",
        refCode: "N/A",
        logo: "projectLogo/sigma-logo.png",
      },
      {
        name: "Hivera",
        funding: "$7M",
        backers: "IPN Foundation, TON Incubator",
        expectedTGE: "Jan - feb",
        joinLink: "https://t.me/Hiverabot/app?startapp=7340846ac",
        refCode: "7340846ac",
        logo: "projectLogo/hivera-logo.png",
      },
      {
        name: "Midas",
        funding: "$13.5M",
        backers: "Framework Ventures, BlockTower Capital",
        expectedTGE: "Q1 2025",
        joinLink: "https://t.me/MidasRWA_bot/app?startapp=ref_1f161856-5364-4da0-af5c-9a087c1e7eee",
        refCode: "ref_1f161856-5364-4da0-af5c-9a087c1e7eee",
        logo: "projectLogo/midas-logo.png",
      },
      {
        name: "UXUY Wallet",
        funding: "$10M",
        backers: "Binance Labs, Bixin Ventures, Matrix Partners",
        expectedTGE: "Q1 2025",
        joinLink: "https://t.me/UXUYbot/app?startapp=A_5156288114_inviteEarn",
        refCode: "N/A",
        logo: "projectLogo/uxuy-logo.png",
      },
      {
        name: "Vooi app",
        funding: "TBA",
        backers: "Binance Labs...",
        expectedTGE: "Q1 2025",
        joinLink: "https://t.me/VooiAppBot/vooi?startapp=frenIDzkxkX2q",
        refCode: "N/A",
        logo: "projectLogo/vooi-logo.png",
      },
      {
        name: "Birds",
        funding: "NOA",
        backers: "Sui",
        expectedTGE: "Q1 2025",
        joinLink: "https://t.me/birdx2_bot/birdx?startapp=5156288114",
        refCode: "N/A",
        logo: "projectLogo/birds-logo.png",
      },
      {
        name: "Zoo",
        funding: "NOA",
        backers: "X-Empire",
        expectedTGE: "Q1 2025",
        joinLink: "t.me/zoo_story_bot/game?startapp=ref5156288114",
        refCode: "N/A",
        logo: "projectLogo/zoo-logo.png",
      },
      {
        name: "Unite",
        funding: "$3M",
        backers: "Coinbase ventures, OKX ventures ,Solana ventures",
        expectedTGE: "Q2 2025",
        joinLink: "https://t.me/unite_io_bot/Llamas?startapp=ref_fbfgciibbe",
        refCode: "N/A",
        logo: "projectLogo/unite-logo.png",
      },
    ],
  },

  {
    title: "DePIN projects",
    projects: [
      {
        name: "Grass",
        funding: "$5M",
        backers: "HackVC",
        expectedTGE: "Q1 2025",
        joinLink: "https://app.getgrass.io/register?referralCode=uMm14UCminsTwxu",
        refCode: "uMm14UCminsTwxu",
        logo: "projectLogo/grass-logo.png",
      },
      {
        name: "Dawn",
        funding: "$2.5M",
        backers: "VanEck Ventures and VanEck's Digital Assets Alpha Fund",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://www.dawninternet.com/",
        refCode: "2uvnrua9",
        logo: "projectLogo/dawn-logo.png",
      },
      {
        name: "NodePay",
        funding: "$7M",
        backers: "Animoca Brands, Mirana, OKX Ventures...",
        expectedTGE: "Q1 2025",
        joinLink: "https://app.nodepay.ai/register?ref=B5BVvMreJy8EpyU",
        refCode: "B5BVvMreJy8EpyU",
        logo: "projectLogo/nodepay-logo.png",
      },
      {
        name: "Bless Network",
        funding: "$1M+ TBA",
        backers: "TBA",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://bless.network/dashboard?ref=8DZ9QB",
        refCode: "8DZ9QB",
        logo: "projectLogo/bless-logo.png",
      },
      {
        name: "Gradient Network",
        funding: "TBA",
        backers: "TBA",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://app.gradient.network/dashboard",
        refCode: "4WP5EI",
        logo: "projectLogo/gradient-logo.png",
      },
      {
        name: "OpenLoop Network",
        funding: "$15M",
        backers: "HackVC",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://openloop.so/auth/register?ref=ol220ace48",
        refCode: "ol220ace48",
        logo: "projectLogo/openloop-logo.png",
      },
      {
        name: "BlockMesh Network",
        funding: "$65M",
        backers: "M31 Capital, Fractis",
        expectedTGE: "Q2 2025",
        joinLink: "https://openloop.so/auth/register?ref=ol220ace48",
        refCode: "ol220ace48",
        logo: "projectLogo/blockmesh-logo.png",
      },
      {
        name: "MeshChain",
        funding: "NOA",
        backers: "NOA",
        expectedTGE: "Q2 2025",
        joinLink: "https://app.meshchain.ai?ref=W113AS39R9P7",
        refCode: "W113AS39R9P7",
        logo: "projectLogo/meshChain-logo.png",
      },
      {
        name: "Pipe Network",
        funding: "NOA",
        backers: "NOA",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://pipecdn.app/",
        refCode: "N/A",
        logo: "projectLogo/pipe-logo.png",
      },
    ],
  },

  {
    title: "Web testnet",
    projects: [
      {
        name: "Open Ledger",
        funding: "$8M",
        backers: "Hashkey capital,Polychain capital and other",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://testnet.openledger.xyz/?referral_code=7hor44g5hi",
        refCode: "7hor44g5hi",
        logo: "projectLogo/openldger-logo.png",
      },
      {
        name: "Rumble video sharing platform",
        funding: "$775M",
        backers: "Tether(company behind USDT)",
        expectedTGE: "Q2-Q3 2025",
        joinLink: "https://rumble.com/register/cryptoCatch",
        refCode: "cryptoCatch",
        logo: "projectLogo/rumble-logo.png",
      },
      {
        name: "Humanity protocol",
        funding: "$35M",
        backers: "Blockchain, Digital Identity, Privacy Technologies",
        expectedTGE: "Q1-Q2 2025",
        joinLink: "https://testnet.humanity.org/login?ref=vinithp03",
        refCode: "vinithp03",
        logo: "projectLogo/humanity-logo.png",
      },
      {
        name: "Soneium testnet",
        funding: "_",
        backers: "Sony",
        expectedTGE: "Q2 2025",
        joinLink: "https://bridge.soneium.org/en/testnet",
        refCode: "N/A",
        logo: "projectLogo/soneium-logo.png",
      },
      {
        name: "Hemi testnet",
        funding: "$15M",
        backers: "Binance Labs, Cypher Capital",
        expectedTGE: "Q2 2025",
        joinLink: "https://points.absinthe.network/hemi/d/dashboard",
        refCode: "N/A",
        logo: "projectLogo/hemi-logo.png",
      },
      {
        name: "Chainbase Genesis",
        funding: "$16.5M",
        backers: "M31 Capital, NGC Ventures, Interop, and Frachtis",
        expectedTGE: "Q2 2025",
        joinLink: "https://genesis.chainbase.com/referral?referral_code=OXVS40JL8",
        refCode: "OXVS40JL8",
        logo: "projectLogo/chainbase-logo.png",
      },
      {
        name: "Zen Chain",
        funding: "$200M",
        backers: "Jun capital, The Gem and others",
        expectedTGE: "Q2 2025",
        joinLink: "https://zenquest.zenchain.io?referral=5wPBWa1ZwNMZqUBpDRSiARmTv-C3yYJwk3mn7mVMnyc",
        refCode: "N/A",
        logo: "projectLogo/zenchain-logo.png",
      },
    ],
  },
];

